name: Validate main
on:
  push:
    branches:
      - "main"

jobs:
  validate-maven-build:
    uses: entur/abt-gha-public/.github/workflows/maven-open-source-verify.yml@1
    with:
      java-version: 21
